<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class KotaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $kota = [
            ['nama_kota' => 'Banda Aceh', 'provinsi' => 'Aceh'],
            ['nama_kota' => 'Langsa', 'provinsi' => 'Aceh'],
            ['nama_kota' => 'Lhokseumawe', 'provinsi' => 'Aceh'],
            ['nama_kota' => 'Sabang', 'provinsi' => 'Aceh'],
            ['nama_kota' => 'Subulussalam', 'provinsi' => 'Aceh'],
            ['nama_kota' => 'Denpasar', 'provinsi' => 'Bali'],
            ['nama_kota' => 'Pangkalpinang', 'provinsi' => 'Bangka Belitung'],
            ['nama_kota' => 'Cilegon', 'provinsi' => 'Banten'],
            ['nama_kota' => 'Serang', 'provinsi' => 'Banten'],
            ['nama_kota' => 'Tangerang Selatan', 'provinsi' => 'Banten'],
            ['nama_kota' => 'Tangerang', 'provinsi' => 'Banten'],
            ['nama_kota' => 'Bengkulu', 'provinsi' => 'Bengkulu'],
            ['nama_kota' => 'Yogyakarta', 'provinsi' => 'DI Yogyakarta'],
            ['nama_kota' => 'Jakarta Barat', 'provinsi' => 'DKI Jakarta'],
            ['nama_kota' => 'Jakarta Pusat', 'provinsi' => 'DKI Jakarta'],
            ['nama_kota' => 'Jakarta Selatan', 'provinsi' => 'DKI Jakarta'],
            ['nama_kota' => 'Jakarta Timur', 'provinsi' => 'DKI Jakarta'],
            ['nama_kota' => 'Jakarta Utara', 'provinsi' => 'DKI Jakarta'],
            ['nama_kota' => 'Gorontalo', 'provinsi' => 'Gorontalo'],
            ['nama_kota' => 'Sungai Penuh', 'provinsi' => 'Jambi'],
            ['nama_kota' => 'Jambi', 'provinsi' => 'Jambi'],
            ['nama_kota' => 'Bandung', 'provinsi' => 'Jawa Barat'],
            ['nama_kota' => 'Bekasi', 'provinsi' => 'Jawa Barat'],
            ['nama_kota' => 'Bogor', 'provinsi' => 'Jawa Barat'],
            ['nama_kota' => 'Cimahi', 'provinsi' => 'Jawa Barat'],
            ['nama_kota' => 'Cirebon', 'provinsi' => 'Jawa Barat'],
            ['nama_kota' => 'Depok', 'provinsi' => 'Jawa Barat'],
            ['nama_kota' => 'Sukabumi', 'provinsi' => 'Jawa Barat'],
            ['nama_kota' => 'Tasikmalaya', 'provinsi' => 'Jawa Barat'],
            ['nama_kota' => 'Banjar', 'provinsi' => 'Jawa Barat'],
            ['nama_kota' => 'Magelang', 'provinsi' => 'Jawa Tengah'],
            ['nama_kota' => 'Pekalongan', 'provinsi' => 'Jawa Tengah'],
            ['nama_kota' => 'Salatiga', 'provinsi' => 'Jawa Tengah'],
            ['nama_kota' => 'Semarang', 'provinsi' => 'Jawa Tengah'],
            ['nama_kota' => 'Surakarta', 'provinsi' => 'Jawa Tengah'],
            ['nama_kota' => 'Tegal', 'provinsi' => 'Jawa Tengah'],
            ['nama_kota' => 'Batu', 'provinsi' => 'Jawa Timur'],
            ['nama_kota' => 'Blitar', 'provinsi' => 'Jawa Timur'],
            ['nama_kota' => 'Kediri', 'provinsi' => 'Jawa Timur'],
            ['nama_kota' => 'Madiun', 'provinsi' => 'Jawa Timur'],
            ['nama_kota' => 'Malang', 'provinsi' => 'Jawa Timur'],
            ['nama_kota' => 'Mojokerto', 'provinsi' => 'Jawa Timur'],
            ['nama_kota' => 'Pasuruan', 'provinsi' => 'Jawa Timur'],
            ['nama_kota' => 'Probolinggo', 'provinsi' => 'Jawa Timur'],
            ['nama_kota' => 'Surabaya', 'provinsi' => 'Jawa Timur'],
            ['nama_kota' => 'Pontianak', 'provinsi' => 'Kalimantan Barat'],
            ['nama_kota' => 'Singkawang', 'provinsi' => 'Kalimantan Barat'],
            ['nama_kota' => 'Banjarbaru', 'provinsi' => 'Kalimantan Selatan'],
            ['nama_kota' => 'Banjarmasin', 'provinsi' => 'Kalimantan Selatan'],
            ['nama_kota' => 'Palangka Raya', 'provinsi' => 'Kalimantan Tengah'],
            ['nama_kota' => 'Balikpapan', 'provinsi' => 'Kalimantan Timur'],
            ['nama_kota' => 'Bontang', 'provinsi' => 'Kalimantan Timur'],
            ['nama_kota' => 'Samarinda', 'provinsi' => 'Kalimantan Timur'],
            ['nama_kota' => 'Nusantara', 'provinsi' => 'Kalimantan Timur'],
            ['nama_kota' => 'Tarakan', 'provinsi' => 'Kalimantan Utara'],
            ['nama_kota' => 'Batam', 'provinsi' => 'Kepulauan Riau'],
            ['nama_kota' => 'Tanjungpinang', 'provinsi' => 'Kepulauan Riau'],
            ['nama_kota' => 'Bandar Lampung', 'provinsi' => 'Lampung'],
            ['nama_kota' => 'Metro', 'provinsi' => 'Lampung'],
            ['nama_kota' => 'Ternate', 'provinsi' => 'Maluku Utara'],
            ['nama_kota' => 'Tidore Kepulauan', 'provinsi' => 'Maluku Utara'],
            ['nama_kota' => 'Ambon', 'provinsi' => 'Maluku'],
            ['nama_kota' => 'Tual', 'provinsi' => 'Maluku'],
            ['nama_kota' => 'Bima', 'provinsi' => 'Nusa Tenggara Barat'],
            ['nama_kota' => 'Mataram', 'provinsi' => 'Nusa Tenggara Barat'],
            ['nama_kota' => 'Kupang', 'provinsi' => 'Nusa Tenggara Timur'],
            ['nama_kota' => 'Sorong', 'provinsi' => 'Papua Barat Daya'],
            ['nama_kota' => 'Jayapura', 'provinsi' => 'Papua'],
            ['nama_kota' => 'Dumai', 'provinsi' => 'Riau'],
            ['nama_kota' => 'Pekanbaru', 'provinsi' => 'Riau'],
            ['nama_kota' => 'Makassar', 'provinsi' => 'Sulawesi Selatan'],
            ['nama_kota' => 'Palopo', 'provinsi' => 'Sulawesi Selatan'],
            ['nama_kota' => 'Parepare', 'provinsi' => 'Sulawesi Selatan'],
            ['nama_kota' => 'Palu', 'provinsi' => 'Sulawesi Tengah'],
            ['nama_kota' => 'Baubau', 'provinsi' => 'Sulawesi Tenggara'],
            ['nama_kota' => 'Kendari', 'provinsi' => 'Sulawesi Tenggara'],
            ['nama_kota' => 'Bitung', 'provinsi' => 'Sulawesi Utara'],
            ['nama_kota' => 'Kotamobagu', 'provinsi' => 'Sulawesi Utara'],
            ['nama_kota' => 'Manado', 'provinsi' => 'Sulawesi Utara'],
            ['nama_kota' => 'Tomohon', 'provinsi' => 'Sulawesi Utara'],
            ['nama_kota' => 'Bukittinggi', 'provinsi' => 'Sumatera Barat'],
            ['nama_kota' => 'Padang', 'provinsi' => 'Sumatera Barat'],
            ['nama_kota' => 'Padang Panjang', 'provinsi' => 'Sumatera Barat'],
            ['nama_kota' => 'Pariaman', 'provinsi' => 'Sumatera Barat'],
            ['nama_kota' => 'Payakumbuh', 'provinsi' => 'Sumatera Barat'],
            ['nama_kota' => 'Sawahlunto', 'provinsi' => 'Sumatera Barat'],
            ['nama_kota' => 'Solok', 'provinsi' => 'Sumatera Barat'],
            ['nama_kota' => 'Lubuklinggau', 'provinsi' => 'Sumatera Selatan'],
            ['nama_kota' => 'Pagar Alam', 'provinsi' => 'Sumatera Selatan'],
            ['nama_kota' => 'Palembang', 'provinsi' => 'Sumatera Selatan'],
            ['nama_kota' => 'Prabumulih', 'provinsi' => 'Sumatera Selatan'],
            ['nama_kota' => 'Binjai', 'provinsi' => 'Sumatera Utara'],
            ['nama_kota' => 'Gunungsitoli', 'provinsi' => 'Sumatera Utara'],
            ['nama_kota' => 'Medan', 'provinsi' => 'Sumatera Utara'],
            ['nama_kota' => 'Padangsidimpuan', 'provinsi' => 'Sumatera Utara'],
            ['nama_kota' => 'Pematangsiantar', 'provinsi' => 'Sumatera Utara'],
            ['nama_kota' => 'Sibolga', 'provinsi' => 'Sumatera Utara'],
            ['nama_kota' => 'Tanjungbalai', 'provinsi' => 'Sumatera Utara'],
            ['nama_kota' => 'Tebing Tinggi', 'provinsi' => 'Sumatera Utara'],            
        ];

        DB::table('kotas')->insert($kota);
    }
}
